[Round2] Step2 - joo
yagom-academy/swift-starter-Round2 pull request #780
Opened 2024-08-19 08:06 UTC by joo945

@jaemuYeo 
잼킹! Step2 PR이에요!

# 고민한 부분
## 처음에 만든 코드
<img width="630" alt="스크린샷 2024-08-19 오후 4 35 23" src="https://github.com/user-attachments/assets/0261d86d-79af-43c6-9938-d49be938c6dc">
<img width="495" alt="스크린샷 2024-08-19 오후 4 35 39" src="https://github.com/user-attachments/assets/4ef9e77b-0899-4ede-9f96-902b9566ecdb">

- 먼저 난수를 생성하는 함수를 만들고 순서도의 진행 방향처럼 6개의 수가 제대로 들어갔는지에 대한 검증에 있어 많은 어려움을 겪었습니다.
- 랜덤으로 생성된 로또 번호와 내 로또번호를 비교하여 상황에 맞는 문자를 출력하기 위해 if 문과 교집합을 사용하였습니다.
- 가끔 4개 혹은 5개의 수가 들어가는 것을 확인하고 이것을 방지하기 위해 randomNumberCheck()이란 함수를 만들어 6개의 수가 들어가지 않을 경우 다시 수를 생성하는 작업을 수행하게 만들었습니다. 하지만 제대로 된 작동을 하지 않았습니다..
- randomNumberCheck() 함수에 repeat - while 문과 while 문을 각각 사용하여 수정했지만 무한 루프에 빠지는 문제가 생겨 아무것도 출력이 되지 않는 문제점이 있었습니다.
- 랜덤으로 생성된 수가 몇 개가 들어갔는지를 떠나 방금 생성된 수가 들어가지 않는 문제점과 제대로 카운트되지 않는다는 문제점을 발견했습니다.

## 첫번째 수정본
<img width="669" alt="스크린샷 2024-08-19 오후 4 18 38" src="https://github.com/user-attachments/assets/4cdafedf-9ff3-40c3-99c2-1a98e73c5751">

- 첫 번째 코드를 전체적으로 수정하였습니다.
- 먼저 무한 루프를 해결하기 위해 randomNumberCheck() 함수 내에서 if 문을 제거 후 while randomNumberCount < 6 조건을 사용하여 randomLottoNumber에 6개의 고유한 숫자가 들어갈 때까지 반복하게 했습니다.
- 그리고 또 다른 문제였던 랜덤 한 수가 들어오면 몇 개의 수가 들어왔는지 제대로 카운트되지 않던 문제는 randomNumberCount를 상수에서 변수로 변경해 주었고 randomNumberCheck() 함수 내에 작성해 주었습니다.
- while 문으로 매번 숫자를 추가할 때 randomNumberCount를 업데이트하여, 중복 숫자가 발생했을 때도 while 루프가 정상적으로 작동하여 무한 루프에 더 이상 빠지지 않았습니다.
- 무한 루프 문제는 결괏값이 계속 0으로 나와서 조건을 충족하지 못하여 무한 루프에 빠진 것으로 보였고, 제대로 된 카운트가 되지 않던 문제는 함수 밖에 상수 형태로 위치해있었고 그로 인해 제대로 된 초기화가 되지 않았다고 생각했습니다.

## 최종 완성본
<img width="665" alt="스크린샷 2024-08-19 오후 4 19 15" src="https://github.com/user-attachments/assets/337da508-ee5c-475b-8fe4-d6904922b1dc">

- 첫 번째 수정본에서 6개의 수가 제대로 들어갔는지 확인하는 randomNumberCheck() 함수와 랜덤 한 수를 생성하는 createRandomLottoNumber() 함수의 기능적 차이는 거의 없다고 생각이 들었고 어떻게 보면 같은 일을 두 번 수행하여 자원 낭비라 생각이 들었습니다.
- 그래서 수의 개수를 확인하는 randomNumberCheck() 함수와 randomNumberCount 변수를 제거 후 createRandomLottoNumber() 함수를 수정해 주었습니다.
- createRandomLottoNumber() 함수 내에서 for 문 대신 while 문을 사용하였고 randomLottoNumber.count를 변수로 만들어 두는 대신 바로 카운트할 수 있게 조건으로 두었습니다.
- randomLottoNumber.count가 6이 될 때까지 반복하여 숫자를 추가하도록 하였고 이를 통해 중복된 숫자가 발생하더라도, 6개의 고유한 숫자가 생성되고, 4 ~ 5개의 수가 들어가는 문제도 발생하지 않았습니다.

2024-08-20 05:33 UTC, jaemuYeo requested changes
오우!! 코드 리팩토링을 단계별로 잘 정리해주신게 너무 좋네요 👍
다만 현재 실행 예시와 다른 부분이 있어 해당 부분을 해결 후에 
코드를 다시 한 번 살펴보도록 하겠습니다 🙏

주어진 예시와 동일하게 동작하는 것이 가장 중요한 문제입니다!
<img width="353" alt="스크린샷 2024-08-20 오후 2 32 17" src="https://github.com/user-attachments/assets/18989e1e-57af-4eb5-89c7-d0e08e2229be">

실행예시에서는 겹치는 번호가 배열에서 벗겨져 숫자만 출력되고있으나
현재 배열안에 감싸져 있는 결과를 확인했어요.
해당 부분 해결 후 PR재요청 주시면 코드에 대한 코멘트도 함께 남겨드리겠습니다!💪

도움이 필요하면 언제든 연락주세요 :)

2024-08-20 10:05 UTC, joo945 commented
@jaemuYeo 

대괄호를 제거하기 위해 joind 함수와 map 함수를 사용하여 제거했습니다!

2024-08-21 08:55 UTC, jaemuYeo requested changes
잘 해결해주셨군요!! 👏
관련하여 코멘트 몇 가지남겨두었습니다!
확인 후 다시 한 번 PR요청주셔요 :)

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +var randomLottoNumber: Set<Int> = Set<Int>()
위에 생성한 myLottoNumbers는 컬렉션타입이기에 복수형으로 네이밍해주셨는데
이 곳도 동일하게 복수형으로 해주시면 좋을 것 같아요 :)

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +func checkLottoResults() {
Result가 아닌 Results인 이유는 무엇인가요~?

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +    while randomLottoNumber.count < 6 {
여러 반복구문 중 while문을 사용하신 이유는 무엇인가요?

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +    randomLottoNumber.removeAll()
해당 코드가 없더라도 계속하여 새로운 번호를 생성하는데 randomLottoNumber의 요소를 지우는 이유가 있을까요?🤔

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +        print("축하합니다! 겹치는 번호는 \(numberCheck.map{String($0)}.joined(separator: ", ")) 입니다!")
잘 해결하셨군요!! 👍

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +    else {
else의 위치는 공식문서에서 어디에 두고있을까요?? (컨벤션)

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +        let randomNumber = Int.random(in: 1...45)
`Int.random(in: 1...45)`를 변수에 담아 의미를 부여한 것이 너무 좋네요! 👍

2024-08-21 08:55 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +    let numberCheck: Set<Int> = randomLottoNumber.intersection(myLottoNumbers)
myLottoNumbers를 해당 함수 내부에서 받아버리면 함수의 재사용성이 떨어질 것 같아요.
사용자가 로또번호를 바꿀때마다 myLottoNumbers의 변수를 찾아가 요소들을 수정해줘야하는데
그렇게하지않기위해 어떻게 수정해볼 수 있을까요?

2024-08-21 12:02 UTC, joo945 commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +var randomLottoNumber: Set<Int> = Set<Int>()
randomLottoNumber 를 randomLottoNumbers로 수정했습니다!

2024-08-21 12:05 UTC, joo945 commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +func checkLottoResults() {
결괏값이 여러 개 나올 때도 있어 복수형으로 작성했습니다. 다시 생각해 보니 결괏값으로 번호가 하나 또는 아예 안 나올 수 있다는 생각에 단수형으로 변경해 주었습니다!

2024-08-21 12:17 UTC, joo945 commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +    randomLottoNumber.removeAll()
- 번호가 생성되어 randomNumbers에 들어가고 다음 번호가 생성 시 한번 비워주는 것이 좋다고 생각하여 randomLottoNumber.removeAll()을 작성해 주었습니다.
- randomLottoNumber.removeAll()를 제거 후 테스트를 해보았는데 차이가 없는 것을 확인하고 불필요한 작업이라 생각해 제거해 주었습니다!

2024-08-21 12:17 UTC, joo945 commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +        print("축하합니다! 겹치는 번호는 \(numberCheck.map{String($0)}.joined(separator: ", ")) 입니다!")
감사합니다!

2024-08-21 12:20 UTC, joo945 commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +    else {
공식 문서를 확인해 보니 '{' 또는 '}'의 앞엔 비어있으면 안 된다는 약속을 확인 후 수정해 주었습니다!

2024-08-21 12:20 UTC, joo945 commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +        let randomNumber = Int.random(in: 1...45)
감사합니다!

2024-08-21 14:25 UTC, joo945 commented on CodeStarterCamp_Week2/lottoNumberGeneretor.swift
> +    let numberCheck: Set<Int> = randomLottoNumber.intersection(myLottoNumbers)
@jaemuYeo 

- 함수의 제사 용성을 높이기 위해 로또 번호를 매개변수로 전달할 수 있게 변경해 주었습니다.

- 먼저 checkLottoResult() 함수에 유저가 선택한 로또 번호를 myEnteredLottoNumber 매개변수로 전달되게 해주었고 전역변수였던 randomLottoNumbers를 지역변수로 변경하면서 타입을 제거하고 상수 형태로 변경하면서 createRandomLottoNumber() 함수를 값으로 넣어주었습니다.

- 지역변수로 변경하면서 변수에서 상수로 변경한 이유는 지역변수로 변경되면서 컬렉션 타입을 제거했고 들어온 6개의 수가 변경되지 않게 하기 위해 상수 형태로 변경해 주었습니다.

- createRandomLottoNumber() 함수를 값으로 넣어준 이유는 createRandomLottoNumber() 함수 내부에 checkLottoResult() 함수처럼 전역변수였던 randomLottoNumbers를 지역변수로 그대로 가져와주었고 Set 타입이기 때문에 함수에 Set 타입을 주었습니다. 그리고 randomLottoNumbers로 반환해 주었습니다.

- 이로 인해 createRandomLottoNumber() 함수 안에 지역변수로 있는 randomLottoNumbers에 값이 들어가 있기 때문에 checkLottoResult() 함수에 있는 지역변수 randomLottoNumbers에 createRandomLottoNumber() 함수를 값으로 주었습니다.

- createRandomLottoNumber() 함수에선 상수가 아닌 변수 형태 그대로 지역변수로 가져온 이유는 비어있는 Set 타입이기에 생성된 6개의 값을 매번 실행할 때마다 새롭게 들어가야 되기 때문에 변수 형태를 유지시켜주었습니다.

- 전역변수들을 지역변수로 변경해 주면서 matchMyNumber() 함수도 변경해 주었습니다.

- matchMyNumber() 함수에선 사용자가 선택한 로또번호와 랜덤으로 생성된 번호를 매개변수로 전달하기 위해 각각 myEnteredLottoNumber, randomLottoNumbers 매개변수를 만들어 주었고 Set 타입을 주었습니다. 그리고 교집합에서 받아오던 myLottoNumbers를 myEnteredLottoNumber로 변경해 주었습니다.

- 마지막으로 main.swift에선 함수 호출 부분을 수정해 주었습니다. 먼저 기존에 lottoNumberGeneretor.swift에 전역변수로 있던 myLottoNumbers를 그대로 가져와 주었고 checkLottoResult() 함수의 매개변수 myEnteredLottoNumber에 myLottoNumber를 전달인자로 주었습니다.

- 위처럼 코드를 수정하여 따로 사용자의 로또 번호를 수정할 때 변수를 찾아갈 필요 없이 main.swift에서 바로 수정할 수 있습니다.

2024-08-22 06:52 UTC, jaemuYeo reviewed
Step2도 고생하셨습니다! 👏
여러 질문을 드렸는데 상사하게 잘 답변 남겨주셔서 코드와 joo님의 의도가 잘 전달되었어요 :)
이번 스텝 Merge하겠습니다!
다음 스텝에서 만나요 🙌

2024-08-22 06:52 UTC, merged