[Round2] Step3 - joo
yagom-academy/swift-starter-Round2 pull request #786
Opened 2024-08-26 02:44 UTC by joo945

@jaemuYeo 잼킹! Step3 PR이에요!

# 고민한 부분

## lottoRoundSearch.swift
<img width="879" alt="스크린샷 2024-08-26 오전 11 26 05" src="https://github.com/user-attachments/assets/7248acc9-3976-4892-8bc8-920954cfab12">

- 먼저 각 회차별로 로또 당첨 번호를 저장하는 roundSave 딕셔너리 변수를 만들어 주었습니다.

- roundCount 변수는 현재 회차를 저장하는 변수이고 새로운 회차가 추가될 때마다 1씩 증가합니다.

- lottoRoundSave() 함수는 새로운 회차를 추가 후 번호를 생성하여 roundSave에 저장하는 함수입니다.

- getLottoRoundNumber() 함수는 특정 회차의 로또 번호를 옵셔널로 안전하게 가져오는 함수입니다. 존재하지 않는 회차를 가져올 시 nil을 반환합니다.

- printLottoRound() 함수는 특정 회차와 그 회차의 로또 번호를 출력하는 함수입니다. if let을 사용하여 옵셔널 바인딩을 해주었습니다.

## main.swift
<img width="257" alt="스크린샷 2024-08-26 오전 11 25 18" src="https://github.com/user-attachments/assets/c6c49303-be99-46d3-86e2-d1fb4e1961d2">

- for 문을 사용하여 5회차까지 번호를 생성하여 lottoRoundSave() 함수를 통해 저장합니다.

- 그리고 printLottoRound() 함수를 사용하여 원하는 회차의 로또 번호를 출력합니다.

# 해결하지 못한 점

- 매번 새롭게 번호를 생성하면 같은 회차에 다른 번호가 들어갑니다.

- 따로 사용자 시스템에 로컬로 저장하는 방법을 사용하지 않고 구현하고 싶었습니다 ㅠ

2024-08-26 08:27 UTC, jaemuYeo requested changes
스텝3도 너무 잘해주셨는걸요!! 
해결하지 못한 부분에 대해서는 꼭 신경쓰지 않으셔도 될 것 같아요 :)
지금 구현한 것이 저희가 의도한 부분이기 때문입니다!

딕셔너리를 잘 사용했는지, 옵셔널 바인딩을 잘 처리했는지가 중요했던 문제예요 👍
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다!

2024-08-26 08:27 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoRoundSearch.swift
> +var roundSave: [Int : Set<Int>] = [:]
딕셔너리 타입을 잘 설계해주셨군요!!
많이 분들이 String타입으로 처음에 제출해주셔서 회차와 번호를 나타내는데 왜 문자열로 타입을 설계했는지
물어보는 편이거든요 :)
Int형으로 너무 잘 해주셨어요 👏

2024-08-26 08:27 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoRoundSearch.swift
> +func lottoRoundSave() {
saveLottoRound로 네이밍해주면 좋을 것 같아요!

2024-08-26 08:27 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoRoundSearch.swift
> +    if let lottoNumbers = getLottoRoundNumber(round: round) {
옵셔널 바인딩 중 if-let을 선택하신 이유는 무엇인가요~?

2024-08-28 11:52 UTC, joo945 commented on CodeStarterCamp_Week2/lottoRoundSearch.swift
> +var roundSave: [Int : Set<Int>] = [:]
감사합니다! 굳이 '회차'라는 단어를 넣을 필요 없이 따로 print에 넣어주면 된다고 생각하여 int 타입으로 지정해 주었습니다!

2024-08-28 11:54 UTC, joo945 commented on CodeStarterCamp_Week2/lottoRoundSearch.swift
> +func lottoRoundSave() {
수정해 주었습니다! 네이밍에 좀 더 신경 써볼게요!

2024-08-29 07:20 UTC, jaemuYeo reviewed
Round2도 고생많으셨습니다!!
다음 라운드로 넘어가셔도 좋을 것 같아요 👏🥳
Merge하겠습니다!

2024-08-29 07:20 UTC, jaemuYeo commented on CodeStarterCamp_Week2/lottoRoundSearch.swift
> +    if let lottoNumbers = getLottoRoundNumber(round: round) {
@joo945 
좋은 이유군요!

저는 보통 guard문을 많이 활용하는데요!
guard-let의 가장 큰 이점은 Early exit(빠른 종료)라는 것 입니다.
if문의 경우 조건이 맞지 않으면 else또는 그 다음 흐름으로 로직이 흘러가는 반면
guard문을 통과하지 못할 경우 예외처리 후 곧바로 함수를 종료한다는 것입니다.

각각의 특징이 있으니 상황에 맞게 적절히 활용하시면 좋을 것 같아요 :)

2024-08-29 07:20 UTC, merged